"""01 initial schema

Revision ID: a395a83126be
Revises: 
Create Date: 2026-09-09 21:13:24.026454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a395a83126be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_code'), 'campaigns', ['code'], unique=True)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('lunch_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shrinkage_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('INDOOR', 'OUTDOOR', name='shrinkagetype'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrinkage_categories_code'), 'shrinkage_categories', ['code'], unique=True)
    op.create_index(op.f('ix_shrinkage_categories_type'), 'shrinkage_categories', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WFM_ANALYST', 'TEAM_LEAD', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'LEAVE', 'TERMINATED', name='employeestatus'), nullable=False),
    sa.Column('weekly_hours_contract', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_campaign_id'), 'employees', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sa.Enum('VOICE', 'CHAT', 'EMAIL', 'BACKOFFICE', name='channel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_campaign_id'), 'skills', ['campaign_id'], unique=False)
    op.create_table('sla_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_level_target_pct', sa.Float(), nullable=False),
    sa.Column('answer_time_threshold_seconds', sa.Float(), nullable=False),
    sa.Column('exclude_short_abandon', sa.Boolean(), nullable=False),
    sa.Column('short_abandon_threshold_seconds', sa.Float(), nullable=False),
    sa.Column('extra_rules_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_profiles_campaign_id'), 'sla_profiles', ['campaign_id'], unique=False)
    op.create_table('actual_performance_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval_start', sa.Time(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('offered', sa.Float(), nullable=False),
    sa.Column('handled', sa.Float(), nullable=False),
    sa.Column('abandoned', sa.Float(), nullable=False),
    sa.Column('talk_time_seconds', sa.Float(), nullable=False),
    sa.Column('hold_time_seconds', sa.Float(), nullable=False),
    sa.Column('acw_seconds', sa.Float(), nullable=False),
    sa.Column('agents_staffed', sa.Float(), nullable=False),
    sa.Column('paid_hours', sa.Float(), nullable=False),
    sa.Column('import_batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_performance_raw_campaign_id'), 'actual_performance_raw', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_actual_performance_raw_date'), 'actual_performance_raw', ['date'], unique=False)
    op.create_index(op.f('ix_actual_performance_raw_import_batch_id'), 'actual_performance_raw', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_actual_performance_raw_skill_id'), 'actual_performance_raw', ['skill_id'], unique=False)
    op.create_table('capacity_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_hc', sa.Float(), nullable=False),
    sa.Column('required_hc', sa.Float(), nullable=False),
    sa.Column('hiring', sa.Float(), nullable=False),
    sa.Column('transfers_in', sa.Float(), nullable=False),
    sa.Column('transfers_out', sa.Float(), nullable=False),
    sa.Column('attrition_pct', sa.Float(), nullable=False),
    sa.Column('absenteeism_pct', sa.Float(), nullable=False),
    sa.Column('projected_hc', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_plans_campaign_id'), 'capacity_plans', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_capacity_plans_period'), 'capacity_plans', ['period'], unique=False)
    op.create_index(op.f('ix_capacity_plans_skill_id'), 'capacity_plans', ['skill_id'], unique=False)
    op.create_table('config_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'CAMPAIGN', 'SKILL', name='configscope'), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_parameters_key'), 'config_parameters', ['key'], unique=False)
    op.create_index(op.f('ix_config_parameters_scope'), 'config_parameters', ['scope'], unique=False)
    op.create_table('daily_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('forecast_volume', sa.Float(), nullable=False),
    sa.Column('forecast_aht_seconds', sa.Float(), nullable=False),
    sa.Column('actual_volume', sa.Float(), nullable=True),
    sa.Column('actual_aht_seconds', sa.Float(), nullable=True),
    sa.Column('required_hc', sa.Float(), nullable=False),
    sa.Column('scheduled_hc', sa.Float(), nullable=False),
    sa.Column('actual_hc', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_forecasts_campaign_id'), 'daily_forecasts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_daily_forecasts_date'), 'daily_forecasts', ['date'], unique=False)
    op.create_index(op.f('ix_daily_forecasts_skill_id'), 'daily_forecasts', ['skill_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'skill_id')
    )
    op.create_table('forecast_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.Enum('LTF', 'STF', name='forecastversiontype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['forecast_versions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_versions_campaign_id'), 'forecast_versions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_forecast_versions_is_current'), 'forecast_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_forecast_versions_skill_id'), 'forecast_versions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_forecast_versions_version_type'), 'forecast_versions', ['version_type'], unique=False)
    op.create_table('interval_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval_start', sa.Time(), nullable=False),
    sa.Column('interval_end', sa.Time(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('forecast_volume', sa.Float(), nullable=False),
    sa.Column('actual_volume', sa.Float(), nullable=True),
    sa.Column('forecast_aht_seconds', sa.Float(), nullable=False),
    sa.Column('actual_aht_seconds', sa.Float(), nullable=True),
    sa.Column('required_hc', sa.Float(), nullable=False),
    sa.Column('scheduled_hc', sa.Float(), nullable=False),
    sa.Column('actual_hc', sa.Float(), nullable=True),
    sa.Column('service_level_pct', sa.Float(), nullable=True),
    sa.Column('asa_seconds', sa.Float(), nullable=True),
    sa.Column('occupancy_pct', sa.Float(), nullable=True),
    sa.Column('abandon_rate_pct', sa.Float(), nullable=True),
    sa.Column('staffing_gap', sa.Float(), nullable=True),
    sa.Column('overtime_required_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interval_forecasts_campaign_id'), 'interval_forecasts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_interval_forecasts_date'), 'interval_forecasts', ['date'], unique=False)
    op.create_index(op.f('ix_interval_forecasts_skill_id'), 'interval_forecasts', ['skill_id'], unique=False)
    op.create_table('overtime_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='periodtype'), nullable=False),
    sa.Column('period_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_hours', sa.Float(), nullable=False),
    sa.Column('available_hours', sa.Float(), nullable=False),
    sa.Column('gap_hours', sa.Float(), nullable=False),
    sa.Column('ot_required_hours', sa.Float(), nullable=False),
    sa.Column('ot_actual_hours', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_plans_campaign_id'), 'overtime_plans', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_overtime_plans_period_key'), 'overtime_plans', ['period_key'], unique=False)
    op.create_index(op.f('ix_overtime_plans_period_type'), 'overtime_plans', ['period_type'], unique=False)
    op.create_index(op.f('ix_overtime_plans_skill_id'), 'overtime_plans', ['skill_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_entries_campaign_id'), 'schedule_entries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_date'), 'schedule_entries', ['date'], unique=False)
    op.create_index(op.f('ix_schedule_entries_employee_id'), 'schedule_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_skill_id'), 'schedule_entries', ['skill_id'], unique=False)
    op.create_table('shrinkage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['shrinkage_categories.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrinkage_records_campaign_id'), 'shrinkage_records', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_shrinkage_records_category_id'), 'shrinkage_records', ['category_id'], unique=False)
    op.create_index(op.f('ix_shrinkage_records_date'), 'shrinkage_records', ['date'], unique=False)
    op.create_index(op.f('ix_shrinkage_records_employee_id'), 'shrinkage_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shrinkage_records_skill_id'), 'shrinkage_records', ['skill_id'], unique=False)
    op.create_table('ltf_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_version_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('forecast_volume', sa.Float(), nullable=False),
    sa.Column('forecast_aht_seconds', sa.Float(), nullable=False),
    sa.Column('aht_required_seconds', sa.Float(), nullable=False),
    sa.Column('occupancy_required_pct', sa.Float(), nullable=False),
    sa.Column('service_level_target_pct', sa.Float(), nullable=False),
    sa.Column('asa_target_seconds', sa.Float(), nullable=False),
    sa.Column('headcount_required', sa.Float(), nullable=False),
    sa.Column('paid_hours', sa.Float(), nullable=False),
    sa.Column('productive_hours', sa.Float(), nullable=False),
    sa.Column('production_hours', sa.Float(), nullable=False),
    sa.Column('waiting_hours', sa.Float(), nullable=False),
    sa.Column('indoor_shrinkage_pct', sa.Float(), nullable=False),
    sa.Column('outdoor_shrinkage_pct', sa.Float(), nullable=False),
    sa.Column('total_shrinkage_pct', sa.Float(), nullable=False),
    sa.Column('available_hours', sa.Float(), nullable=False),
    sa.Column('staffing_gap', sa.Float(), nullable=False),
    sa.Column('overtime_required_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['forecast_version_id'], ['forecast_versions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ltf_forecasts_campaign_id'), 'ltf_forecasts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ltf_forecasts_forecast_version_id'), 'ltf_forecasts', ['forecast_version_id'], unique=False)
    op.create_index(op.f('ix_ltf_forecasts_month'), 'ltf_forecasts', ['month'], unique=False)
    op.create_index(op.f('ix_ltf_forecasts_skill_id'), 'ltf_forecasts', ['skill_id'], unique=False)
    op.create_index(op.f('ix_ltf_forecasts_year'), 'ltf_forecasts', ['year'], unique=False)
    op.create_table('stf_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_version_id', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('aht_seconds', sa.Float(), nullable=False),
    sa.Column('occupancy_pct', sa.Float(), nullable=False),
    sa.Column('shrinkage_pct', sa.Float(), nullable=False),
    sa.Column('service_level_target_pct', sa.Float(), nullable=False),
    sa.Column('headcount_required', sa.Float(), nullable=False),
    sa.Column('paid_hours', sa.Float(), nullable=False),
    sa.Column('productive_hours', sa.Float(), nullable=False),
    sa.Column('production_hours', sa.Float(), nullable=False),
    sa.Column('waiting_hours', sa.Float(), nullable=False),
    sa.Column('overtime_required_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['forecast_version_id'], ['forecast_versions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stf_forecasts_campaign_id'), 'stf_forecasts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_stf_forecasts_forecast_version_id'), 'stf_forecasts', ['forecast_version_id'], unique=False)
    op.create_index(op.f('ix_stf_forecasts_iso_week'), 'stf_forecasts', ['iso_week'], unique=False)
    op.create_index(op.f('ix_stf_forecasts_iso_year'), 'stf_forecasts', ['iso_year'], unique=False)
    op.create_index(op.f('ix_stf_forecasts_skill_id'), 'stf_forecasts', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stf_forecasts_skill_id'), table_name='stf_forecasts')
    op.drop_index(op.f('ix_stf_forecasts_iso_year'), table_name='stf_forecasts')
    op.drop_index(op.f('ix_stf_forecasts_iso_week'), table_name='stf_forecasts')
    op.drop_index(op.f('ix_stf_forecasts_forecast_version_id'), table_name='stf_forecasts')
    op.drop_index(op.f('ix_stf_forecasts_campaign_id'), table_name='stf_forecasts')
    op.drop_table('stf_forecasts')
    op.drop_index(op.f('ix_ltf_forecasts_year'), table_name='ltf_forecasts')
    op.drop_index(op.f('ix_ltf_forecasts_skill_id'), table_name='ltf_forecasts')
    op.drop_index(op.f('ix_ltf_forecasts_month'), table_name='ltf_forecasts')
    op.drop_index(op.f('ix_ltf_forecasts_forecast_version_id'), table_name='ltf_forecasts')
    op.drop_index(op.f('ix_ltf_forecasts_campaign_id'), table_name='ltf_forecasts')
    op.drop_table('ltf_forecasts')
    op.drop_index(op.f('ix_shrinkage_records_skill_id'), table_name='shrinkage_records')
    op.drop_index(op.f('ix_shrinkage_records_employee_id'), table_name='shrinkage_records')
    op.drop_index(op.f('ix_shrinkage_records_date'), table_name='shrinkage_records')
    op.drop_index(op.f('ix_shrinkage_records_category_id'), table_name='shrinkage_records')
    op.drop_index(op.f('ix_shrinkage_records_campaign_id'), table_name='shrinkage_records')
    op.drop_table('shrinkage_records')
    op.drop_index(op.f('ix_schedule_entries_skill_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_employee_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_date'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_campaign_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_overtime_plans_skill_id'), table_name='overtime_plans')
    op.drop_index(op.f('ix_overtime_plans_period_type'), table_name='overtime_plans')
    op.drop_index(op.f('ix_overtime_plans_period_key'), table_name='overtime_plans')
    op.drop_index(op.f('ix_overtime_plans_campaign_id'), table_name='overtime_plans')
    op.drop_table('overtime_plans')
    op.drop_index(op.f('ix_interval_forecasts_skill_id'), table_name='interval_forecasts')
    op.drop_index(op.f('ix_interval_forecasts_date'), table_name='interval_forecasts')
    op.drop_index(op.f('ix_interval_forecasts_campaign_id'), table_name='interval_forecasts')
    op.drop_table('interval_forecasts')
    op.drop_index(op.f('ix_forecast_versions_version_type'), table_name='forecast_versions')
    op.drop_index(op.f('ix_forecast_versions_skill_id'), table_name='forecast_versions')
    op.drop_index(op.f('ix_forecast_versions_is_current'), table_name='forecast_versions')
    op.drop_index(op.f('ix_forecast_versions_campaign_id'), table_name='forecast_versions')
    op.drop_table('forecast_versions')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_daily_forecasts_skill_id'), table_name='daily_forecasts')
    op.drop_index(op.f('ix_daily_forecasts_date'), table_name='daily_forecasts')
    op.drop_index(op.f('ix_daily_forecasts_campaign_id'), table_name='daily_forecasts')
    op.drop_table('daily_forecasts')
    op.drop_index(op.f('ix_config_parameters_scope'), table_name='config_parameters')
    op.drop_index(op.f('ix_config_parameters_key'), table_name='config_parameters')
    op.drop_table('config_parameters')
    op.drop_index(op.f('ix_capacity_plans_skill_id'), table_name='capacity_plans')
    op.drop_index(op.f('ix_capacity_plans_period'), table_name='capacity_plans')
    op.drop_index(op.f('ix_capacity_plans_campaign_id'), table_name='capacity_plans')
    op.drop_table('capacity_plans')
    op.drop_index(op.f('ix_actual_performance_raw_skill_id'), table_name='actual_performance_raw')
    op.drop_index(op.f('ix_actual_performance_raw_import_batch_id'), table_name='actual_performance_raw')
    op.drop_index(op.f('ix_actual_performance_raw_date'), table_name='actual_performance_raw')
    op.drop_index(op.f('ix_actual_performance_raw_campaign_id'), table_name='actual_performance_raw')
    op.drop_table('actual_performance_raw')
    op.drop_index(op.f('ix_sla_profiles_campaign_id'), table_name='sla_profiles')
    op.drop_table('sla_profiles')
    op.drop_index(op.f('ix_skills_campaign_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_campaign_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shrinkage_categories_type'), table_name='shrinkage_categories')
    op.drop_index(op.f('ix_shrinkage_categories_code'), table_name='shrinkage_categories')
    op.drop_table('shrinkage_categories')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_code'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
