"""02 interval forecast targets

Revision ID: c35734c4834f
Revises: a395a83126be
Create Date: 2026-09-12 08:16:31.334855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c35734c4834f'
down_revision: Union[str, None] = 'a395a83126be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default ajoute manuellement (Postgres refuse NOT NULL sans
    # defaut sur une table non vide ; coherent avec Field(default=0) cote
    # SQLModel).
    op.add_column('interval_forecasts', sa.Column('service_level_target_pct', sa.Float(), nullable=False, server_default='0'))
    op.add_column('interval_forecasts', sa.Column('answer_time_target_seconds', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interval_forecasts', 'answer_time_target_seconds')
    op.drop_column('interval_forecasts', 'service_level_target_pct')
    # ### end Alembic commands ###
